version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_net
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception_net

volumes:
  db_data:

networks:
  inception_net:
