services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - inception_network
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress

  adminer:
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    container_name: adminer
    restart: unless-stopped
    networks:
      - inception_network
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
  redis:
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    networks:
      - inception_network
    volumes:
      - redis_data:/var/lib/redis

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  redis_data:
    driver: local